lista= ('notebook',2000 ,'celular',3000,'carro',100000)
print('_'*35)
print('''         LISTAGEM DE PREÇO''')
print('_'*35)
print(f'{lista[0]}...................R${lista[1]}')
print(f'{lista[2]}....................R${lista[3]}' )
print(f'{lista[4]}....................R${lista[5]}')
print('_'*35)