a =input("digite algo: ")
print('o tipo primitivo é',type(a))
print('so´ tem  espaço: ',a.isspace())
print('é numero: ',a.isnumeric())
print('é alfabetico',a.isalpha())
print('é um nome',a.isidentifier())
print('ele é alfannumerico',a.isalnum())
print('esta em maiuscula',a.isupper())
print('ele esta em minusculo',a.islower())
